#!/usr/bin/env python3
# Generated by Claude Code
"""
FastAPI entrypoint for krknctl scenario identification service
Uses FAISS vector store for scenario matching
Compatible with krknctl OpenAI-style API
"""

import logging
import time
import os
from contextlib import asynccontextmanager
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from utils.faiss_vector_store import FAISSVectorStore
from utils.faiss_document_indexer import FaissDocumentIndexer

# Configure logging first
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
# Configuration from environment
RELEVANCE_THRESHOLD = float(os.getenv("RELEVANCE_THRESHOLD", "0.7"))
GITHUB_REPO = os.getenv(
    "GITHUB_REPO", "https://github.com/tsebastiani/website.git"
)

REPO_PATH = os.getenv("REPO_PATH", "content/en/docs")
PERSIST_DIR = os.getenv("PERSIST_DIR", "faiss_index")
KRKN_HUB_REPO = os.getenv(
    "KRKN_HUB_REPO", "https://github.com/krkn-chaos/krkn-hub"
)
GITHUB_BRANCH = os.getenv(
    "GITHUB_BRANCH", "assist_classifier"
)  # Branch with krkn-hub-scenario tags

KRKN_HUB_BRANCH = os.getenv(
    "KRKN_HUB_BRANCH", None
)  # Optional branch for krkn-hub repo
LOCAL_DOCS_PATH = os.getenv(
    "LOCAL_DOCS_PATH", None
)  # Optional local path instead of cloning
FORCE_REINDEX = os.getenv("FORCE_REINDEX", "false").lower() == "true"

# Global vector store instance
vector_store = None


# krknctl-compatible models (matching OpenAI format)
class ChatMessage(BaseModel):
    role: str
    content: str


class QueryRequest(BaseModel):
    model: str
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.1
    max_tokens: Optional[int] = 512
    stream: Optional[bool] = False


class QueryChoice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: str


class Usage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class QueryResponse(BaseModel):
    id: str
    object: str
    created: int
    model: str
    choices: List[QueryChoice]
    usage: Usage
    scenario_name: Optional[str] = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage application lifespan (startup and shutdown)"""
    global vector_store

    # Startup
    logger.info("Starting krknctl scenario identification service...")
    logger.info(f"Relevance threshold: {RELEVANCE_THRESHOLD}")

    try:
        # Check if index exists and build if necessary
        if FORCE_REINDEX or not os.path.exists(
            os.path.join(PERSIST_DIR, "index.faiss")
        ):
            logger.info("Building new FAISS index...")
            indexer = FaissDocumentIndexer()
            indexer.build_and_save_index(
                github_repo=GITHUB_REPO,
                repo_path=REPO_PATH,
                output_dir=PERSIST_DIR,
                krkn_hub_repo=KRKN_HUB_REPO,
                github_branch=GITHUB_BRANCH,
                krkn_hub_branch=KRKN_HUB_BRANCH,
                local_docs_path=LOCAL_DOCS_PATH,
            )
            logger.info("Index built successfully")
        else:
            logger.info("Using existing index")

        # Load vector store
        vector_store = FAISSVectorStore(PERSIST_DIR)
        logger.info(
            f"Vector store loaded with {len(vector_store.documents)} documents"
        )

    except Exception as e:
        logger.error(f"Failed to initialize vector store: {e}")
        raise

    yield

    # Shutdown
    logger.info("krknctl scenario identification service shutting down...")


# Create FastAPI app with lifespan management
app = FastAPI(
    title="krknctl Scenario Identification Service",
    version="3.0.0",
    description="Vector store-based scenario matching for krknctl using FAISS",
    lifespan=lifespan,
)


def get_user_query_from_messages(messages: List[ChatMessage]) -> str:
    """Extract user query from OpenAI messages format"""
    # Get the last user message
    for message in reversed(messages):
        if message.role == "user":
            return message.content
    return ""


@app.get("/")
async def root():
    """Root endpoint with service information"""
    return {
        "service": "krknctl Scenario Identification",
        "version": "3.0.0",
        "backend": "FAISS vector store",
        "relevance_threshold": RELEVANCE_THRESHOLD,
        "description": "Scenario identification service for "
        "krknctl chaos engineering",
        "endpoints": {"health": "/health", "query": "/v1/chat/completions"},
    }


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    if not vector_store:
        raise HTTPException(
            status_code=503, detail="Vector store not initialized"
        )

    documents_count = len(vector_store.documents) if vector_store else 0

    return {
        "status": "healthy",
        "service": "krknctl-scenario-identification",
        "backend": "FAISS",
        "documents_indexed": documents_count,
        "relevance_threshold": RELEVANCE_THRESHOLD,
    }


@app.post("/v1/chat/completions", response_model=QueryResponse)
async def chat_completions(request: QueryRequest):
    """
    Simplified scenario identification endpoint
    Returns scenario_name if relevance score exceeds threshold
    """
    try:
        if not vector_store:
            raise HTTPException(
                status_code=503, detail="Vector store not initialized"
            )

        if request.stream:
            raise HTTPException(
                status_code=400, detail="Streaming not yet supported"
            )

        # Extract user query from messages
        user_query = get_user_query_from_messages(request.messages)
        if not user_query:
            raise HTTPException(
                status_code=400, detail="No user message found in request"
            )

        # Perform vector similarity search
        query_start_time = time.time()
        documents = vector_store.similarity_search(user_query, k=1)
        query_time = time.time() - query_start_time

        # Extract scenario_name from top result if
        # relevance score is high enough
        scenario_name = None
        relevance_score = 0.0

        if documents and len(documents) > 0:
            top_doc = documents[0]
            relevance_score = top_doc.metadata.get("relevance_score", 0.0)

            if relevance_score >= RELEVANCE_THRESHOLD:
                scenario_name = top_doc.metadata.get("scenario_name")
            else:
                logger.info(
                    f"Relevance score {relevance_score:.3f} "
                    f"below threshold {RELEVANCE_THRESHOLD}"
                )

        # Log performance metrics
        logger.info("=" * 60)
        logger.info("SCENARIO IDENTIFICATION METRICS")
        logger.info("=" * 60)
        logger.info(
            f"Query: {user_query[:100]}"
            f"{'...' if len(user_query) > 100 else ''}"
        )
        logger.info(f"Total Query Time: {query_time:.3f}s")
        logger.info(f"Relevance Score:  {relevance_score:.3f}")
        logger.info(f"Threshold:        {RELEVANCE_THRESHOLD}")
        logger.info(
            f"Scenario Found:   {scenario_name or 'None (below threshold)'}"
        )
        logger.info("=" * 60)

        # Create response with just the query echoed back
        current_time = int(time.time())
        response_id = f"chatcmpl-{current_time}"

        # Simple response format - just echo back minimal info
        response_content = f"Query: {user_query}"
        if scenario_name:
            response_content = f"Scenario: {scenario_name}"

        return QueryResponse(
            id=response_id,
            object="chat.completion",
            created=current_time,
            model=request.model or "faiss-vector-store",
            choices=[
                QueryChoice(
                    index=0,
                    message=ChatMessage(
                        role="assistant", content=response_content
                    ),
                    finish_reason="stop",
                )
            ],
            usage=Usage(
                prompt_tokens=len(user_query.split()),
                completion_tokens=len(response_content.split()),
                total_tokens=len(user_query.split())
                + len(response_content.split()),
            ),
            scenario_name=scenario_name,
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing chat completion: {e}")
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {str(e)}"
        )


# Simplified response model for direct scenario queries
class ScenarioQueryRequest(BaseModel):
    query: str


class ScenarioQueryResponse(BaseModel):
    query: str
    scenario_name: Optional[str] = None


# Legacy endpoint for backward compatibility
@app.post("/query", response_model=ScenarioQueryResponse)
async def legacy_query(request: ScenarioQueryRequest):
    """
    Simple query endpoint that returns only query and scenario_name
    """
    try:
        # Perform vector similarity search
        documents = vector_store.similarity_search(request.query, k=5)

        # Log top 5 results for debugging
        logger.info(f"=== Top 5 results for query: '{request.query}' ===")
        for i, doc in enumerate(documents[:5]):
            score = doc.metadata.get("relevance_score", 0.0)
            scenario = doc.metadata.get("scenario_name", "unknown")
            logger.info(f"  {i+1}. {scenario}: {score:.3f}")

        # Extract scenario_name from top
        # result if relevance score is high enough
        scenario_name = None
        relevance_score = 0.0

        if documents and len(documents) > 0:
            top_doc = documents[0]
            relevance_score = top_doc.metadata.get("relevance_score", 0.0)

            if relevance_score >= RELEVANCE_THRESHOLD:
                scenario_name = top_doc.metadata.get("scenario_name")

        logger.info(
            f"Query: '{request.query}' -> Scenario: "
            f"{scenario_name or 'None'} (score: {relevance_score:.3f})"
        )

        return ScenarioQueryResponse(
            query=request.query, scenario_name=scenario_name
        )

    except Exception as e:
        logger.error(f"Error in query endpoint: {e}")
        raise HTTPException(
            status_code=500, detail=f"Internal server error: {str(e)}"
        )


if __name__ == "__main__":
    import uvicorn

    logger.info("Starting krknctl Scenario Identification Service...")
    uvicorn.run(app, host="0.0.0.0", port=8080, log_level="info")
